type: local
port: 6029
name: local_model_1
log_level: DEBUG
log_file: logs/model_1.log
download_directory: downloads
prometheus_port: 8000
model_size: tiny # for local type
# api_token: "" # for api type
# url: "" # for api type